### ISSUE TITLE
Increasing accuracy of the model upto 99% by using neural networks

### ISSUE THREAD

**Issue by tanya162** [srimani-programmer/Breast-Cancer-Predictor#37]
The accuracy of this model can be increased by using neural networks . This will increase efficiency of this project.

**Comment by tanya162** [comment]
I have worked a lot on neural networks and I have a code that can increase the accuracy , will you please assign me this issue so that I can work on this issue further

**Comment by tiyarocks** [comment]
hey i can work on this issue too! please assign this to me

**Comment by MILIND-RAJ** [comment]
Hi, before asking for assignment of this task to me, I have tried to reach to 99% testing accuracy using neural networks and I have accomplished this task, the model is ready, so you can assign the task to me.

**Comment by Aditi0102** [comment]
Hello.. I want to use various Customised CNN and Inception+CustomisedCNN to try and improve the accuracy to 99%.

**Comment by Simar05519** [comment]
I want to work on this issue. Please assign to me

**Comment by dashingdiptu12345** [comment]
I want to work on this issue,you can assign it to me

**Comment by aayushi1908** [comment]
Hello. I'm Aayushi, a GSSOC'21 participant. I'm eager to work on this issue as I've already worked on a project similar to this. 

In this, I've tweaked a Deep Learning model using DevOps to get the best accuracy--
https://mytask3.blogspot.com/2020/05/task-3-tweaking-architecture.html
https://github.com/aayushi1908/Task-3-MLOPs.git

Please have a look on the above links. My solution to your issue is to combine both of the above projects and your guidance.
Kindly assign this issue to me,
